version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "decklist-front"
s3_bucket = "bornus-bucket"
s3_prefix = "decklist-front"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
