AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  User dashboard, to list documentation for each published features

Parameters:
  mainDomain:
    Type: "String"
    Default: "front.YOURDOMAIN.com"

Resources:
  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Amplify
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'amplify:*'
                Resource: '*'
        - PolicyName: user-dashboard-repository-access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Resource: !GetAtt Repository.Arn
                Action:
                  - "codecommit:*"

  Repository:
    Type: AWS::CodeCommit::Repository
    Properties: 
      RepositoryName: user-dashboard

  AmplifyApp:
    Type: 'AWS::Amplify::App'
    Properties:
      Name: user-dashboard
      Repository: !GetAtt Repository.CloneUrlHttp # !GetAtt Repository.Arn
      Description: Website for partner to have the documentations about each features
      EnvironmentVariables:
        - Name: REACT_APP_API_MANAGEMENT_GATEWAY_NAME
          Value: '{{resolve:ssm:API_MANAGEMENT_GATEWAY_NAME:1}}'
        - Name: REACT_APP_API_MANAGEMENT_GATEWAY_ROOT_URL
          Value: '{{resolve:ssm:API_MANAGEMENT_GATEWAY_ROOT_URL:1}}'
        - Name: REACT_APP_DEVPORTAL_DASHBOARD_APP_CLIENT_WEB
          Value: '{{resolve:ssm:DEVPORTAL_DASHBOARD_APP_CLIENT_WEB:1}}'
        - Name: REACT_APP_DEVPORTAL_DASHBOARD_IDENTITY_POOL
          Value: '{{resolve:ssm:DEVPORTAL_DASHBOARD_IDENTITY_POOL:1}}'
        - Name: REACT_APP_DEVPORTAL_DASHBOARD_USER_POOL
          Value: '{{resolve:ssm:DEVPORTAL_DASHBOARD_USER_POOL:1}}'
        - Name: REACT_APP_DEVPORTAL_REGION
          Value: '{{resolve:ssm:DEVPORTAL_REGION:1}}'
      AutoBranchCreationConfig:
        EnableAutoBranchCreation: False
        EnableAutoBuild: True
      BuildSpec: |-
        version: 0.1
        frontend:
          phases:
            preBuild:
              commands:
                - yarn install
            build:
              commands:
                - yarn run build
          artifacts:
            baseDirectory: build
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
      CustomRules:
        - Source: /<*>
          Target: /index.html
          Status: '404'
      IAMServiceRole: !GetAtt AmplifyRole.Arn

  AmplifyDomain:
    Type: AWS::Amplify::Domain
    Properties:
      DomainName: !Ref mainDomain
      AppId: !GetAtt AmplifyApp.AppId
      SubDomainSettings:
        - Prefix: dashboard
          BranchName: !GetAtt AmplifyBranch.BranchName

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      BranchName: master
      AppId: !GetAtt AmplifyApp.AppId
      Description: master Branch
      EnableAutoBuild: true
      Tags:
        - Key: Branch
          Value: master

  # DNSRecord:
  #   Type: AWS::Route53::RecordSetGroup
  #   Properties:
  #     HostedZoneId: !FindInMap [envVars, hostedZoneId, !Ref stage]
  #     RecordSets:
  #     - Type: A
  #       Name: !Ref DomainName
  #       AliasTarget:
  #         HostedZoneId: !GetAtt DomainName.DistributionHostedZoneId
  #         DNSName: !GetAtt DomainName.DistributionDomainName

Outputs:
  DefaultDomain:
    Value: !GetAtt AmplifyApp.DefaultDomain
  
  RepositoryUrl:
    Value: !GetAtt Repository.CloneUrlHttp

